let arr = [null, true, 500, "javascript"];
console.log(arr);
arr.push(4564);
console.log(arr);
console.log(arr.pop());
console.log(arr);
let arr1 = [1, 2, 3, 4];
arr.push(...arr1);
console.log(arr);
arr.push(arr1);
console.log(arr);
arr.shift();
console.log(arr);
arr.unshift(443, 554, 544);
console.log(arr);
arr.splice(2, 5);
console.log(arr);
arr.pop();
arr.push(...arr);
arr.splice(2, 5, true, 3, 5, 4);
console.log(arr);
arr.reverse();
console.log(arr);
arr.sort();
console.log(arr);
